export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Services } from './Services'
export { default as Prices } from './Prices'
export { default as Team } from './Team'
export { default as Contact } from './Contact'